-- Schema initialization for Hentetjeneste (PostgreSQL-compatible, works with H2 in PostgreSQL mode)

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    role VARCHAR(50) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE children (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    group_name VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    check_in_time TIME,
    check_out_time TIME,
    pickup_status VARCHAR(50),
    pickup_person VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    parent_id BIGINT NOT NULL REFERENCES users(id)
);

CREATE TABLE approved_persons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    relation VARCHAR(255) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    approved_date DATE,
    blocked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    child_id BIGINT NOT NULL REFERENCES children(id)
);

CREATE TABLE incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    severity VARCHAR(50) NOT NULL,
    action_taken TEXT,
    notified_parents BOOLEAN NOT NULL DEFAULT FALSE,
    reported_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    child_id BIGINT NOT NULL REFERENCES children(id),
    reported_by_id BIGINT NOT NULL REFERENCES users(id)
);

CREATE TABLE pickup_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    picked_up_by VARCHAR(255) NOT NULL,
    picked_up_at TIMESTAMP NOT NULL,
    checked_out_time TIME NOT NULL,
    verified_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    child_id BIGINT NOT NULL REFERENCES children(id)
);

CREATE TABLE daily_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    type VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    target_group VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Indexes and constraints
CREATE INDEX idx_children_group ON children(group_name);
CREATE INDEX idx_children_status ON children(status);
CREATE INDEX idx_incidents_child ON incidents(child_id);
CREATE INDEX idx_approved_persons_child ON approved_persons(child_id);
CREATE INDEX idx_pickup_logs_child ON pickup_logs(child_id);
